# Generated by Django 5.2.7 on 2025-10-26 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('aqi_pm25', models.FloatField(blank=True, null=True)),
                ('aqi_pm10', models.FloatField(blank=True, null=True)),
                ('aqi_no2', models.FloatField(blank=True, null=True)),
                ('aqi_co', models.FloatField(blank=True, null=True)),
                ('aqi_o3', models.FloatField(blank=True, null=True)),
                ('overall_aqi', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RouteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=200)),
                ('source_lat', models.FloatField()),
                ('source_lng', models.FloatField()),
                ('destination_name', models.CharField(max_length=200)),
                ('destination_lat', models.FloatField()),
                ('destination_lng', models.FloatField()),
                ('priority', models.CharField(choices=[('shortest', 'Shortest Distance'), ('cleanest', 'Cleanest Air'), ('balanced', 'Balanced')], default='balanced', max_length=20)),
                ('total_distance', models.FloatField()),
                ('estimated_time', models.FloatField()),
                ('average_aqi', models.FloatField()),
                ('route_geometry', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
